### ISSUE TITLE
test您给的模型的时候报错是什么原因，val没有问题.DC_pose_supp_files是不是少一个test.JSON?

### ISSUE THREAD

**Issue by Scheng-xiang** [Pose-Group/DCPose#25]

**Comment by Scheng-xiang** [comment]
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    runner.launch()
  File "/root/code/DCPose/engine/defaults/runner.py", line 63, in launch
    evaluator.exec()
  File "/root/code/DCPose/engine/defaults/evaluator.py", line 20, in exec
    self.eval()
  File "/root/code/DCPose/engine/defaults/evaluator.py", line 73, in eval
    phase=self.phase)
  File "/root/code/DCPose/engine/core/function.py", line 167, in eval
    input_x, input_sup_A, input_sup_B, target_heatmaps, target_heatmaps_weight, meta = next(self.dataloader_iter)
  File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.

**Comment by Scheng-xiang** [comment]
数据集缺少？

**Comment by FRunyang** [comment]
we have provided the file of 'test_box.json', which contains the bounding boxes of test set.

**Comment by Scheng-xiang** [comment]
when i run the command 'python run.py --cfg ../configs/posetimation/DcPose/posetrack17/model_RSN_trained.yaml --test'

erro happend :

Traceback (most recent call last):
File "run.py", line 33, in
main()
File "run.py", line 29, in main
runner.launch()
File "/root/code/DCPose/engine/defaults/runner.py", line 63, in launch
evaluator.exec()
File "/root/code/DCPose/engine/defaults/evaluator.py", line 20, in exec
self.eval()
File "/root/code/DCPose/engine/defaults/evaluator.py", line 73, in eval
phase=self.phase)
File "/root/code/DCPose/engine/core/function.py", line 167, in eval
input_x, input_sup_A, input_sup_B, target_heatmaps, target_heatmaps_weight, meta = next(self.dataloader_iter)
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in next
data = self._next_data()
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
return self._process_data(data)
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
data.reraise()
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.

**Comment by Scheng-xiang** [comment]
> we have provided the file of 'test_box.json', which contains the bounding boxes of test set.

when i run the command 'python run.py --cfg ../configs/posetimation/DcPose/posetrack17/model_RSN_trained.yaml --test'

erro happend :

Traceback (most recent call last):
File "run.py", line 33, in
main()
File "run.py", line 29, in main
runner.launch()
File "/root/code/DCPose/engine/defaults/runner.py", line 63, in launch
evaluator.exec()
File "/root/code/DCPose/engine/defaults/evaluator.py", line 20, in exec
self.eval()
File "/root/code/DCPose/engine/defaults/evaluator.py", line 73, in eval
phase=self.phase)
File "/root/code/DCPose/engine/core/function.py", line 167, in eval
input_x, input_sup_A, input_sup_B, target_heatmaps, target_heatmaps_weight, meta = next(self.dataloader_iter)
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in next
data = self._next_data()
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
return self._process_data(data)
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
data.reraise()
File "/root/anaconda3/envs/DCPose/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
