### ISSUE TITLE
Throws error when I try to train from scratch in posetrack 18

### ISSUE THREAD

**Issue by kawanish** [Pose-Group/DCPose#38]
The below error occurs:

022-04-23 06:32:46 [posetimation.zoo.DcPose.dcpose_rsn] ERROR: => please download pre-trained models first!
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    main()
  File "run.py", line 29, in main
    runner.launch()
  File "/home/awanish/DCPose-main/engine/defaults/runner.py", line 52, in launch
    trainer = DefaultTrainer(self.cfg, self.output_path_dict, PE_Name=self.args.PE_Name)
  File "/home/awanish/DCPose-main/engine/defaults/trainer.py", line 32, in __init__
    self.model = build_model(cfg, phase='train')
  File "/home/awanish/DCPose-main/posetimation/zoo/build.py", line 17, in build_model
    model_instance.init_weights()
  File "/home/awanish/DCPose-main/posetimation/zoo/DcPose/dcpose_rsn.py", line 285, in init_weights
    raise ValueError('{} is not exist!'.format(self.pretrained))
ValueError: /home/awanish/DCPose-main/DcPose_supp_files/pretrained_models/pretrained_.pth is not exist!

there is no file with the name pretrained_.pth given in supp files folder

**Comment by l1teng** [comment]
The same issue from me. Is there any solutions?
